apiVersion: apps/v1 
kind: Deployment
metadata:
  name: test-kubernetes 
  namespace: default
  labels:
    app: test_kubernetes
spec:
  revisionHistoryLimit: 3
  replicas: 1 
  selector:
    matchLabels:
      app: test_kubernetes
  template:
    metadata:
      labels:
        app: test_kubernetes
    spec:
      containers:
      - name: app
        image: tensorflow/tensorflow:latest-devel-py3
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c"]
        args:
         - echo "start";
           git clone https://github.com/maruotto/test_kubernetes;
           cd test_kubernetes;
           pip install -r requirements.txt;
           python server.py;
        ports:
        - containerPort: 8080
          protocol: TCP
