apiVersion: apps/v1 
kind: Deployment
metadata:
  name: glucose-predictor-deployment
  labels:
    app: glucose-predictor
spec:
  replicas: 2
  selector:
    matchLabels:
      app: glucose-predictor
  template:
    metadata:
      labels:
        app: glucose-predictor
    spec:
      containers:
      - name: glucose
        image: nanigo/glucose:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8501