apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: glucose.prediction
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: predict-test-kubernetes
              port:
                number: 8080