apiVersion: v1
kind: Service
metadata:
  name: glucose-predictor-service
  labels:
    app: glucose-predictor
spec:
  selector:
    app: glucose-predictor
  type: NodePort
  ports:
    - name: http
      port: 8501
      targetPort: 8501


